# Generated by Django 2.0.2 on 2018-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180228_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
