# Generated by Django 2.0.2 on 2018-02-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_votes_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Comments'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Posts'),
        ),
    ]
