# Generated by Django 2.0.2 on 2018-03-01 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20180228_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentPost', to='boards.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostBoard', to='boards.SubReddits'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='Boards_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubsBoard', to='boards.SubReddits'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votes',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VoteComment', to='boards.Comments'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoteUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votes',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VotePost', to='boards.Posts'),
        ),
    ]
