# Generated by Django 2.0.2 on 2018-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180301_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
