# Generated by Django 2.0.2 on 2018-03-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20180301_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
