# Generated by Django 2.0.2 on 2018-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20180302_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='from_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='votes',
            name='from_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
